<?php
use Framework\Gui\Gui;
use Framework\Util\Escaper;

echo $form->html();

if ($error !== null) {
    Gui::panel('Error', '<p>'.Escaper::escapeHtml($error).'</p>', 'danger');
}

if (is_array($functions) && count($functions) > 0) {
    ob_start();
    echo '<form method="post">';
    echo '<p><select name="call_function" id="call_function">';

    foreach ($functions as $func => $params) {
        $selected = $call_function === $func ? ' selected ' : '';
        echo '<option '.$selected.'value="'.$func.'">'.$func.'</option>';
    }

    echo '</select></p>';

    foreach ($functions as $func => $params) {
        echo '<p id="params_'.$func.'" style="display: none;">';
        foreach ($params as $key => $param) {
            $value = '';
            $jtaChecked = '';
            if ($call_function === $func) {
                $param_value = $call_params[$key] ?? '';
                if (is_array($param_value)) {
                    $param_value = json_encode($param_value);
                    $jtaChecked = ' checked';
                }
                $value = ' value="'.Escaper::escapeHtml($param_value).'"';
            }

            echo '<strong>'.$param.':</strong> <input type="text" name="param_'.$func.'_'.$param.'"'.$value.'> ';
            echo '<input type="checkbox" name="array_'.$func.'_'.$param.'"'.$jtaChecked.'> <label for="array_'.$func.'_'.$param.'">JSON to array</label>';
            echo '<br>';
        }
        echo '</p>';
    }

    echo '<p><input class="btn btn-primary" type="submit" value="Call"></p>';
    echo '</form>';

    Gui::panel('Call', ob_get_clean());
}

if ($response !== null) {
    ob_start();
    echo '<pre>'.Escaper::escapeHtml(print_r($response, true)).'</pre>';
    Gui::panel('Response', ob_get_clean());
}

if ($raw_request !== null ) {
    ob_start();
    echo '<pre>'.Escaper::escapeHtml(print_r($raw_request, true)).'</pre>';
    Gui::panel('Raw Request', ob_get_clean());
}

if ($raw_response !== null ) {
    ob_start();
    echo '<pre>'.Escaper::escapeHtml(print_r($raw_response, true)).'</pre>';
    Gui::panel('Raw Response', ob_get_clean());
}

ob_start();
if (is_array($function_defs) && count($function_defs) > 0) {
  echo '<p>';
  foreach ($function_defs as $def) {
    echo "{$def}<br>";
  }
  echo '</p>';
} else {
  echo '<p>No functions</p>';
}

Gui::panel('Functions', ob_get_clean());

ob_start();
if (is_array($type_defs) && count($type_defs) > 0) {
  echo '<p>';
  foreach ($type_defs as $def) {
    echo "{$def}<br>";
  }
  echo '</p>';
} else {
  echo '<p>No types</p>';
}

Gui::panel('Types', ob_get_clean());
?>
<script>
    let callFunction = document.getElementById('call_function');
    let currentFunctionId = 0;

    function showParams() {
        document.getElementById('params_'+callFunction.options[currentFunctionId].value).style.display = 'none';
        currentFunctionId = callFunction.options.selectedIndex;
        document.getElementById('params_'+callFunction.options[currentFunctionId].value).style.display = '';
    }

    if (callFunction !== null) {
        showParams();
        callFunction.addEventListener('change', showParams);
    }
</script>

